name: Test

on:
  push:
   branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  checks: write
  contents: write

jobs:
  run-test:
    name: Run linters
    runs-on: windows-latest

    steps:
      - name: Check out of Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run test
        run: npm test

      - name: Run build
        run: npm run build
